// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Hit is one match inside one snapshot.
 */
export class Hit {
    /**
     * Snapshot and Stamp identify which snapshot held it.
     */
    "snapshot": string;
    "stamp": string;

    /**
     * LivePath is where this would be restored to, in the running system's
     * terms, which is what the user recognises.
     */
    "livePath": string;
    "name": string;
    "isDir": boolean;
    "size": number;
    "modTime": string;

    /** Creates a new Hit instance. */
    constructor($$source: Partial<Hit> = {}) {
        if (!("snapshot" in $$source)) {
            this["snapshot"] = "";
        }
        if (!("stamp" in $$source)) {
            this["stamp"] = "";
        }
        if (!("livePath" in $$source)) {
            this["livePath"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("modTime" in $$source)) {
            this["modTime"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Hit instance from a string or object.
     */
    static createFrom($$source: any = {}): Hit {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Hit($$parsedSource as Partial<Hit>);
    }
}
