// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Change is one difference between the snapshot and the live filesystem.
 */
export class Change {
    /**
     * RelPath is relative to the compared directory, which is what the UI
     * shows. AbsLive and AbsSnapshot are the full paths on each side.
     */
    "relPath": string;
    "absLive": string;
    "absSnapshot": string;
    "status": Status;
    "isDir": boolean;
    "snapSize": number;
    "liveSize": number;
    "snapModTime": string;
    "liveModTime": string;

    /** Creates a new Change instance. */
    constructor($$source: Partial<Change> = {}) {
        if (!("relPath" in $$source)) {
            this["relPath"] = "";
        }
        if (!("absLive" in $$source)) {
            this["absLive"] = "";
        }
        if (!("absSnapshot" in $$source)) {
            this["absSnapshot"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = Status.$zero;
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }
        if (!("snapSize" in $$source)) {
            this["snapSize"] = 0;
        }
        if (!("liveSize" in $$source)) {
            this["liveSize"] = 0;
        }
        if (!("snapModTime" in $$source)) {
            this["snapModTime"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("liveModTime" in $$source)) {
            this["liveModTime"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Change instance from a string or object.
     */
    static createFrom($$source: any = {}): Change {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Change($$parsedSource as Partial<Change>);
    }
}

/**
 * Result is the outcome of a comparison.
 */
export class Result {
    "root": string;
    "snapshotDir": string;
    "changes": Change[];

    /**
     * Errors records paths that could not be read, usually because macOS
     * privacy protection covers them. A comparison continues past them rather
     * than failing, so a protected subfolder cannot hide the rest of the answer.
     */
    "errors": string[];
    "scanned": number;

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("snapshotDir" in $$source)) {
            this["snapshotDir"] = "";
        }
        if (!("changes" in $$source)) {
            this["changes"] = [];
        }
        if (!("errors" in $$source)) {
            this["errors"] = [];
        }
        if (!("scanned" in $$source)) {
            this["scanned"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("changes" in $$parsedSource) {
            $$parsedSource["changes"] = $$createField2_0($$parsedSource["changes"]);
        }
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField3_0($$parsedSource["errors"]);
        }
        return new Result($$parsedSource as Partial<Result>);
    }
}

/**
 * Status describes what happened to one path between the snapshot and now.
 */
export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * Same means the file is unchanged by whichever comparison was requested.
     */
    Same = "same",

    /**
     * Modified means the file exists on both sides with different contents.
     */
    Modified = "modified",

    /**
     * OnlyInSnapshot means the file has been deleted since the snapshot. This
     * is the status that matters after an accidental wipe.
     */
    OnlyInSnapshot = "onlyInSnapshot",

    /**
     * OnlyOnDisk means the file was created after the snapshot was taken.
     */
    OnlyOnDisk = "onlyOnDisk",

    /**
     * TypeChanged means a name now refers to a different kind of object, for
     * instance a directory replaced by a symlink.
     */
    TypeChanged = "typeChanged",

    /**
     * NotExamined is a directory whose contents were not walked far enough to
     * say. It exists because the honest answer to "did anything under here
     * change?" is sometimes "I did not look", and reporting that as unchanged is
     * how this application would tell somebody their work was safe when it had
     * not checked.
     */
    NotExamined = "notExamined",
};

// Private type creation functions
const $$createType0 = Change.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
