// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Result reports what a restore produced.
 */
export class Result {
    /**
     * Destination is where the restored copy actually landed, which is not the
     * requested path in SideBySide mode.
     */
    "destination": string;

    /**
     * BackedUp is where a pre-existing file was moved to, if any.
     */
    "backedUp"?: string;
    "files": number;
    "dirs": number;
    "bytes": number;

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("destination" in $$source)) {
            this["destination"] = "";
        }
        if (!("files" in $$source)) {
            this["files"] = 0;
        }
        if (!("dirs" in $$source)) {
            this["dirs"] = 0;
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Result($$parsedSource as Partial<Result>);
    }
}
