// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BrowseService reads directories, on the live disk and inside snapshots.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DirectoryStatus answers whether anything under one directory has changed.
 *
 * Separate from Merged because the two have opposite costs. A listing is two
 * directory reads and is instant; a directory's verdict may be a walk of
 * everything beneath it, and only in the case where nothing has changed — a
 * difference is found and returned the moment it appears. Asking for them
 * together would make every listing as slow as its slowest folder.
 *
 * The window calls this once per folder row and fills each in as it answers, so
 * a large untouched tree delays nothing but its own row.
 */
export function DirectoryStatus(snapshotName: string, livePath: string): $CancellablePromise<string> {
    return $Call.ByID(638270053, snapshotName, livePath);
}

/**
 * Home is the starting point for browsing.
 *
 * While mounts are simulated it is the seed directory, because that is the only
 * place a faked snapshot differs from the live disk. Opening on the home folder
 * instead would show a wall of identical rows and look like the comparison was
 * broken.
 */
export function Home(): $CancellablePromise<string> {
    return $Call.ByID(63276391);
}

/**
 * ListLive reads a directory on the running system.
 */
export function ListLive(livePath: string): $CancellablePromise<$models.Listing> {
    return $Call.ByID(3553074810, livePath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListSnapshot reads a directory as it was when the snapshot was taken. Paths
 * are given and returned in live terms; the mapping to the mountpoint is
 * internal.
 */
export function ListSnapshot(snapshotName: string, livePath: string): $CancellablePromise<$models.Listing> {
    return $Call.ByID(4050716252, snapshotName, livePath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Locate answers the question that matters after a deletion: which snapshots
 * still hold this path. Only mounted snapshots can be inspected, so the result
 * says which ones were checked rather than implying an answer for the rest.
 */
export function Locate(livePath: string): $CancellablePromise<$models.Presence[]> {
    return $Call.ByID(1872916882, livePath).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Merged reads a folder from the snapshot and from the live disk and returns
 * the two combined. It reads two directories and never descends, so it stays
 * immediate however large the tree below is; Compare is the recursive answer.
 */
export function Merged(snapshotName: string, livePath: string, includeSame: boolean): $CancellablePromise<$models.MergedListing> {
    return $Call.ByID(3217692856, snapshotName, livePath, includeSame).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * RevealInFinder opens a path in the Finder. Snapshots are mounted nobrowse, so
 * this is how a mounted snapshot is opened in a normal file window.
 */
export function RevealInFinder(snapshotName: string, livePath: string): $CancellablePromise<void> {
    return $Call.ByID(1913126866, snapshotName, livePath);
}

// Private type creation functions
const $$createType0 = $models.Listing.createFrom;
const $$createType1 = $models.Presence.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.MergedListing.createFrom;
