// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BrowseService reads directories, on the live disk and inside snapshots.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DirectoryStatus(device: string, snapshotName: string, livePath: string): $CancellablePromise<$models.FolderVerdict> {
    return $Call.ByID(638270053, device, snapshotName, livePath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Home is the starting point for browsing.
 *
 * While mounts are simulated it is the seed directory, because that is the only
 * place a faked snapshot differs from the live disk. Opening on the home folder
 * instead would show a wall of identical rows and look like the comparison was
 * broken.
 * Home is where browsing a volume starts: the home directory on the startup disk,
 * and the volume's own root anywhere else.
 *
 * Another volume has no home directory, and the whole of it is what someone
 * plugged in to look at. Starting at a home path that does not exist there would
 * open an empty listing and look like an empty snapshot.
 */
export function Home(device: string): $CancellablePromise<string> {
    return $Call.ByID(63276391, device);
}

/**
 * ListLive reads a directory on the running system.
 */
export function ListLive(livePath: string): $CancellablePromise<$models.Listing> {
    return $Call.ByID(3553074810, livePath).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListSnapshot reads a directory as it was when the snapshot was taken. Paths
 * are given and returned in live terms; the mapping to the mountpoint is
 * internal.
 */
export function ListSnapshot(device: string, snapshotName: string, livePath: string): $CancellablePromise<$models.Listing> {
    return $Call.ByID(4050716252, device, snapshotName, livePath).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Locate answers the question that matters after a deletion: which snapshots
 * still hold this path. Only mounted snapshots can be inspected, so the result
 * says which ones were checked rather than implying an answer for the rest.
 */
export function Locate(livePath: string): $CancellablePromise<$models.Presence[]> {
    return $Call.ByID(1872916882, livePath).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Merged reads a folder from the snapshot and from the live disk and returns
 * the two combined. It reads two directories and never descends, so it stays
 * immediate however large the tree below is; Compare is the recursive answer.
 */
export function Merged(device: string, snapshotName: string, livePath: string, includeSame: boolean): $CancellablePromise<$models.MergedListing> {
    return $Call.ByID(3217692856, device, snapshotName, livePath, includeSame).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * RevealInFinder opens a path in the Finder. Snapshots are mounted nobrowse, so
 * this is how a mounted snapshot is opened in a normal file window.
 */
export function RevealInFinder(device: string, snapshotName: string, livePath: string): $CancellablePromise<void> {
    return $Call.ByID(1913126866, device, snapshotName, livePath);
}

// Private type creation functions
const $$createType0 = $models.FolderVerdict.createFrom;
const $$createType1 = $models.Listing.createFrom;
const $$createType2 = $models.Presence.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.MergedListing.createFrom;
