// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService gives the window the settings file.
 *
 * It exists so that preferences survive the installation they were set in. The
 * theme used to live in the webview's localStorage, which is per-installation by
 * construction: set dark in a development build, install the release, and it was
 * light again with nothing to explain why.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Get reads the configuration.
 */
export function Get(): $CancellablePromise<$models.ConfigView> {
    return $Call.ByID(1339402708).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * IgnoreFolder stops the bulk-deletion tripwire counting deletions in a folder.
 *
 * The reason for wanting this arrives while looking at a warning that should not
 * have happened — a browser clearing its cache, a build directory being emptied —
 * so the interface offers it there rather than in a settings screen someone would
 * have to go and find.
 *
 * The folder is stored with separators around it, which is what makes it a
 * fragment rather than a prefix: "/Caches/" matches that folder wherever it
 * appears, and a folder given here matches itself and anything under it without
 * matching a sibling whose name merely starts the same way.
 */
export function IgnoreFolder(folder: string): $CancellablePromise<$models.ConfigView> {
    return $Call.ByID(3171666770, folder).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * IgnoreInChangeDetection adds a pattern to the list of paths that comparing a
 * snapshot with the live disk does not look inside.
 *
 * Deliberately not the same list as IgnoreFolder, which is the bulk-deletion
 * watcher's. That one answers "deletions here do not count as a burst"; this one
 * answers "do not read this when comparing". They would usually hold the same
 * paths, which is why they are kept apart — sharing them would mean changing what
 * you are warned about in order to change what gets walked.
 */
export function IgnoreInChangeDetection(pattern: string): $CancellablePromise<$models.ConfigView> {
    return $Call.ByID(2752022164, pattern).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetLanguage records which language both surfaces should speak.
 *
 * Written to the settings file rather than only to the window, because the menu
 * bar is drawn in Go and reads the same file: the settings watcher redraws it,
 * so a language chosen in the window reaches the menu bar without a relaunch.
 */
export function SetLanguage(code: string): $CancellablePromise<void> {
    return $Call.ByID(1967604466, code);
}

/**
 * SetTheme stores the appearance choice and nothing else.
 *
 * Narrow on purpose. A general "write this whole config" from the window would
 * let a stale copy of the settings — one read before the file changed on disk —
 * overwrite everything else in it. Each setting the interface can change gets its
 * own call, so concurrent edits can only collide on the same field.
 */
export function SetTheme(theme: string): $CancellablePromise<void> {
    return $Call.ByID(3523442845, theme);
}

/**
 * SetTripwireSensitivity records how readily a burst of deletions counts as one
 * worth snapshotting.
 *
 * It takes effect on the watcher's next run rather than immediately: the tripwire
 * is a separate process that launchd restarts, and it reads this at startup. That
 * is worth saying in the interface, because a setting that appears to apply and
 * does not is worse than one that says when it will.
 */
export function SetTripwireSensitivity(name: string): $CancellablePromise<void> {
    return $Call.ByID(3584836541, name);
}

/**
 * StopIgnoringFolder undoes IgnoreFolder.
 *
 * Removing is as important as adding: an ignore list nobody can see or shorten is
 * a list that quietly grows until the tripwire watches nothing, and the failure
 * is silent by construction.
 *
 * Named for what it does to the ignore list rather than "WatchFolder", which it
 * used to be called. There is now a list of directories the tripwire watches, and
 * a method called WatchFolder that does not add to it is a trap.
 */
export function StopIgnoringFolder(fragment: string): $CancellablePromise<$models.ConfigView> {
    return $Call.ByID(1262749405, fragment).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * StopIgnoringInChangeDetection removes a pattern, so those paths are compared
 * again.
 *
 * Matched exactly rather than by what it resolves to, because a pattern is not a
 * path: "node_modules" names every directory of that name at any depth, and there
 * is nothing to resolve it against.
 */
export function StopIgnoringInChangeDetection(pattern: string): $CancellablePromise<$models.ConfigView> {
    return $Call.ByID(788130005, pattern).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * TripwireSensitivities are the settings on offer, coarsest first, and which one
 * is in force.
 */
export function TripwireSensitivities(): $CancellablePromise<[$models.TripwireSensitivity[], string]> {
    return $Call.ByID(3898489713).then(($result: any) => {
        $result[0] = $$createType2($result[0]);
        return $result;
    });
}

/**
 * UnwatchDirectory takes a directory off the list the tripwire watches.
 *
 * Matched on what it resolves to as well as on how it was written, so a row shown
 * as "~/projects" is removed by the button beside it whichever of the two forms
 * the file happens to hold.
 */
export function UnwatchDirectory(dir: string): $CancellablePromise<$models.ConfigView> {
    return $Call.ByID(2096027625, dir).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * WatchDirectory adds a directory to the list the bulk-deletion tripwire watches.
 *
 * This is the list that decides what is watched at all. Before it there was one
 * answer — the whole home directory — and the only control was an ignore list
 * chasing whatever had most recently made a noise. Naming what to protect is both
 * smaller and answerable: someone knows which of their directories holds work
 * they could not reproduce.
 *
 * Stored as given, "~" and all, so that the settings file says back what was
 * typed and keeps meaning it on a machine where the home directory moves. It is
 * resolved when it is read.
 */
export function WatchDirectory(dir: string): $CancellablePromise<$models.ConfigView> {
    return $Call.ByID(3815344338, dir).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * WatchedDirectories lists what the tripwire is set to watch.
 */
export function WatchedDirectories(): $CancellablePromise<$models.WatchedDirectory[]> {
    return $Call.ByID(1841734381).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ConfigView.createFrom;
const $$createType1 = $models.TripwireSensitivity.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.WatchedDirectory.createFrom;
const $$createType4 = $Create.Array($$createType3);
