// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService gives the window the settings file.
 *
 * It exists so that preferences survive the installation they were set in. The
 * theme used to live in the webview's localStorage, which is per-installation by
 * construction: set dark in a development build, install the release, and it was
 * light again with nothing to explain why.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Get reads the configuration.
 */
export function Get(): $CancellablePromise<$models.ConfigView> {
    return $Call.ByID(1339402708).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetTheme stores the appearance choice and nothing else.
 *
 * Narrow on purpose. A general "write this whole config" from the window would
 * let a stale copy of the settings — one read before the file changed on disk —
 * overwrite everything else in it. Each setting the interface can change gets its
 * own call, so concurrent edits can only collide on the same field.
 */
export function SetTheme(theme: string): $CancellablePromise<void> {
    return $Call.ByID(3523442845, theme);
}

// Private type creation functions
const $$createType0 = $models.ConfigView.createFrom;
