// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService gives the window the settings file.
 *
 * It exists so that preferences survive the installation they were set in. The
 * theme used to live in the webview's localStorage, which is per-installation by
 * construction: set dark in a development build, install the release, and it was
 * light again with nothing to explain why.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Get reads the configuration.
 */
export function Get(): $CancellablePromise<$models.ConfigView> {
    return $Call.ByID(1339402708).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * IgnoreFolder stops the bulk-deletion tripwire counting deletions in a folder.
 *
 * The reason for wanting this arrives while looking at a warning that should not
 * have happened — a browser clearing its cache, a build directory being emptied —
 * so the interface offers it there rather than in a settings screen someone would
 * have to go and find.
 *
 * The folder is stored with separators around it, which is what makes it a
 * fragment rather than a prefix: "/Caches/" matches that folder wherever it
 * appears, and a folder given here matches itself and anything under it without
 * matching a sibling whose name merely starts the same way.
 */
export function IgnoreFolder(folder: string): $CancellablePromise<$models.ConfigView> {
    return $Call.ByID(3171666770, folder).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetTheme stores the appearance choice and nothing else.
 *
 * Narrow on purpose. A general "write this whole config" from the window would
 * let a stale copy of the settings — one read before the file changed on disk —
 * overwrite everything else in it. Each setting the interface can change gets its
 * own call, so concurrent edits can only collide on the same field.
 */
export function SetTheme(theme: string): $CancellablePromise<void> {
    return $Call.ByID(3523442845, theme);
}

/**
 * WatchFolder undoes IgnoreFolder.
 *
 * Removing is as important as adding: an ignore list nobody can see or shorten is
 * a list that quietly grows until the tripwire watches nothing, and the failure
 * is silent by construction.
 */
export function WatchFolder(fragment: string): $CancellablePromise<$models.ConfigView> {
    return $Call.ByID(68344599, fragment).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ConfigView.createFrom;
