// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DiffService compares a folder in a snapshot against the same folder now, or
 * against the same folder in another snapshot.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as diffs$0 from "../internal/diffs/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel stops the comparison in progress, if there is one.
 */
export function Cancel(): $CancellablePromise<void> {
    return $Call.ByID(3719167439);
}

/**
 * Compare walks the snapshot and the live disk and returns the differences.
 */
export function Compare(req: $models.CompareRequest): $CancellablePromise<diffs$0.Result> {
    return $Call.ByID(2127969472, req).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CompareSnapshots reports what changed between two snapshots under LivePath.
 *
 * Which snapshot is the older one is decided by the snapshots' own timestamps,
 * not by the order the arguments arrived in. A change between two snapshots has
 * no inherent direction, and getting it backwards inverts every row silently: a
 * file the user recovered would be reported as one they lost. That is a far worse
 * failure than any refusal, so argument order is treated as an intention to be
 * checked rather than as a fact. The check is free and authoritative, because
 * tmutil puts the instant a snapshot was taken in its name.
 *
 * Two snapshots cannot tie. The stamp is a whole second of local time and it *is*
 * the snapshot's identity, so equal timestamps mean one snapshot named twice,
 * which is refused below.
 */
export function CompareSnapshots(req: $models.CompareSnapshotsRequest): $CancellablePromise<$models.SnapshotComparison> {
    return $Call.ByID(3081644357, req).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = diffs$0.Result.createFrom;
const $$createType1 = $models.SnapshotComparison.createFrom;
