// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as diffs$0 from "../internal/diffs/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as find$0 from "../internal/find/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vfs$0 from "../internal/vfs/models.js";

/**
 * CompareRequest is one comparison.
 */
export class CompareRequest {
    "snapshot": string;

    /**
     * Device names the volume the snapshot is on, empty meaning the startup disk.
     * A snapshot name does not say: the same date exists on every volume mounted
     * when it was taken.
     */
    "device": string;

    /**
     * LivePath is the folder to compare, in the running system's terms.
     */
    "livePath": string;

    /**
     * Deep compares contents by hash instead of size and timestamp. It is
     * accurate and slow; the shallow default is the right one for a first look.
     */
    "deep": boolean;

    /**
     * IncludeSame keeps unchanged files in the result.
     */
    "includeSame": boolean;

    /** Creates a new CompareRequest instance. */
    constructor($$source: Partial<CompareRequest> = {}) {
        if (!("snapshot" in $$source)) {
            this["snapshot"] = "";
        }
        if (!("device" in $$source)) {
            this["device"] = "";
        }
        if (!("livePath" in $$source)) {
            this["livePath"] = "";
        }
        if (!("deep" in $$source)) {
            this["deep"] = false;
        }
        if (!("includeSame" in $$source)) {
            this["includeSame"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompareRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CompareRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CompareRequest($$parsedSource as Partial<CompareRequest>);
    }
}

/**
 * CompareSnapshotsRequest asks what changed between two snapshots.
 *
 * Older and Newer state the roles the caller intends. They are not taken on
 * trust — see CompareSnapshots — but naming them rather than numbering them
 * means a caller cannot pass two snapshots without having thought about which
 * way round the answer will read.
 */
export class CompareSnapshotsRequest {
    "older": string;
    "newer": string;

    /**
     * Device names the volume BOTH snapshots are on. Comparing across volumes is
     * not offered: the two would be different trees, and the differences reported
     * would be between two disks rather than between two moments.
     */
    "device": string;

    /**
     * LivePath is the folder to compare, in the running system's terms. Both
     * sides are translated from it, so the same place in the tree is compared in
     * each snapshot however their mountpoints differ.
     */
    "livePath": string;

    /**
     * Deep compares contents by hash instead of size and timestamp, as for a
     * comparison against the live disk.
     */
    "deep": boolean;

    /**
     * IncludeSame keeps unchanged files in the result.
     */
    "includeSame": boolean;

    /** Creates a new CompareSnapshotsRequest instance. */
    constructor($$source: Partial<CompareSnapshotsRequest> = {}) {
        if (!("older" in $$source)) {
            this["older"] = "";
        }
        if (!("newer" in $$source)) {
            this["newer"] = "";
        }
        if (!("device" in $$source)) {
            this["device"] = "";
        }
        if (!("livePath" in $$source)) {
            this["livePath"] = "";
        }
        if (!("deep" in $$source)) {
            this["deep"] = false;
        }
        if (!("includeSame" in $$source)) {
            this["includeSame"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompareSnapshotsRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CompareSnapshotsRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CompareSnapshotsRequest($$parsedSource as Partial<CompareSnapshotsRequest>);
    }
}

/**
 * ConfigView is the settings plus where they are stored, because a settings screen
 * that will not tell you which file it is editing is a settings screen you cannot
 * fix by hand.
 */
export class ConfigView {
    "path": string;
    "config": config$0.Config;

    /**
     * Error is a configuration file that exists and could not be read. The
     * defaults are returned alongside it rather than nothing at all, so the window
     * still works while saying what is wrong.
     */
    "error": string;

    /** Creates a new ConfigView instance. */
    constructor($$source: Partial<ConfigView> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("config" in $$source)) {
            this["config"] = (new config$0.Config());
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigView instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfigView {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField1_0($$parsedSource["config"]);
        }
        return new ConfigView($$parsedSource as Partial<ConfigView>);
    }
}

/**
 * EventLogScan is what one pass over a volume's event log found.
 */
export class EventLogScan {
    /**
     * Offered is how many candidate paths the log named.
     */
    "offered": number;

    /**
     * Found is how many of them turned out to differ from the snapshot and were
     * recorded. Always the smaller number, usually by a lot: the log records that
     * something was written, not that the result differs from what a snapshot
     * holds.
     */
    "found": number;

    /**
     * Usable is false when the log said nothing this pass can rely on — no
     * history yet, a log that was wiped, or one that admitted to dropping events.
     * It is never a reason to conclude anything is unchanged.
     */
    "usable": boolean;

    /**
     * Why says what happened, for the window and for the log.
     */
    "why"?: string;

    /** Creates a new EventLogScan instance. */
    constructor($$source: Partial<EventLogScan> = {}) {
        if (!("offered" in $$source)) {
            this["offered"] = 0;
        }
        if (!("found" in $$source)) {
            this["found"] = 0;
        }
        if (!("usable" in $$source)) {
            this["usable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EventLogScan instance from a string or object.
     */
    static createFrom($$source: any = {}): EventLogScan {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EventLogScan($$parsedSource as Partial<EventLogScan>);
    }
}

/**
 * FileVersions is one file as two chosen versions hold it, ready to be shown
 * side by side.
 *
 * Left and Right rather than Snapshot and Live, because the right side is no
 * longer always the disk: it is whichever version was picked to compare against,
 * and another mounted snapshot is as valid a choice as the live filesystem. The
 * left side is always the snapshot being browsed.
 */
export class FileVersions {
    /**
     * Left and Right are the two texts. Empty with Readable false means the file
     * was not returned as text at all, and the reason is in Note.
     */
    "left": string;
    "right": string;

    /**
     * Readable is false for a file that is binary or too large. Both are ordinary
     * outcomes rather than errors: a JPEG has no line-by-line difference to show
     * and a 500MB log would take the window down with it.
     */
    "readable": boolean;
    "note"?: string;

    /**
     * The figures are given whatever happens, because "2.1 MB became 2.4 MB" is
     * still an answer about a file that cannot be diffed.
     */
    "leftSize": number;
    "rightSize": number;

    /**
     * Missing sides are how a file created or deleted between the two versions
     * appears.
     */
    "leftExists": boolean;
    "rightExists": boolean;

    /**
     * RightLabel names what the right side turned out to be, so the window can say
     * so without repeating the rule for resolving it.
     *
     * A snapshot's stamp, or empty for the live disk. Empty rather than a phrase
     * because the window interpolates this into a sentence — "no longer in
     * {{version}}" — and it used to be the English words "the live disk", which
     * arrived intact in the middle of a German sentence. A stamp is the same in
     * every language; prose is not, and the window has its own word for this one.
     */
    "rightLabel": string;

    /**
     * Kind is how the window should show this, and is one of:
     *
     * 	"text"    lines to compare, in Left and Right
     * 	"image"   two pictures, in LeftImage and RightImage
     * 	"binary"  no lines to compare; Note says so
     * 	"absent"  nothing on either side
     * 	"large"   text, but past the size worth rendering; Note says so
     *
     * Readable stays what it was — true only for text — so nothing that already
     * checks it starts rendering an image into a line-by-line view. The two agree
     * by construction, and diffKindsTest pins that they do.
     */
    "kind": string;

    /**
     * The two pictures, as data URIs, when Kind is "image". Inlined rather than
     * served from a URL because a snapshot's mountpoint is not reachable from the
     * web view, and an image the window cannot fetch is no better than none.
     */
    "leftImage"?: string;
    "rightImage"?: string;

    /**
     * Pixel dimensions, when they could be read. Empty for a format the Go side
     * has no decoder for — the web view can still draw several of those, and a
     * picture without its dimensions beats no picture.
     */
    "leftDims"?: string;
    "rightDims"?: string;

    /**
     * Identical says the two sides are byte-for-byte the same. Worth stating for
     * an image, where two versions can look alike on screen and a diff of lines
     * is not available to settle it.
     */
    "identical": boolean;

    /** Creates a new FileVersions instance. */
    constructor($$source: Partial<FileVersions> = {}) {
        if (!("left" in $$source)) {
            this["left"] = "";
        }
        if (!("right" in $$source)) {
            this["right"] = "";
        }
        if (!("readable" in $$source)) {
            this["readable"] = false;
        }
        if (!("leftSize" in $$source)) {
            this["leftSize"] = 0;
        }
        if (!("rightSize" in $$source)) {
            this["rightSize"] = 0;
        }
        if (!("leftExists" in $$source)) {
            this["leftExists"] = false;
        }
        if (!("rightExists" in $$source)) {
            this["rightExists"] = false;
        }
        if (!("rightLabel" in $$source)) {
            this["rightLabel"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("identical" in $$source)) {
            this["identical"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileVersions instance from a string or object.
     */
    static createFrom($$source: any = {}): FileVersions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileVersions($$parsedSource as Partial<FileVersions>);
    }
}

export class Finding {
    "level": Level;
    "title": string;
    "detail": string;

    /**
     * Action names a button the interface can offer, empty when there is
     * nothing to click.
     */
    "action"?: string;

    /**
     * Kind says what the finding is ABOUT, where Level says how bad it is. Two
     * findings can share a level and have nothing else in common, so anything
     * choosing an icon or an illustration keys off this rather than off Level —
     * otherwise every warning looks identical.
     */
    "kind": string;

    /** Creates a new Finding instance. */
    constructor($$source: Partial<Finding> = {}) {
        if (!("level" in $$source)) {
            this["level"] = Level.$zero;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Finding instance from a string or object.
     */
    static createFrom($$source: any = {}): Finding {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Finding($$parsedSource as Partial<Finding>);
    }
}

/**
 * DirectoryStatus answers whether anything under one directory has changed.
 *
 * Separate from Merged because the two have opposite costs. A listing is two
 * directory reads and is instant; a directory's verdict may be a walk of
 * everything beneath it, and only in the case where nothing has changed — a
 * difference is found and returned the moment it appears. Asking for them
 * together would make every listing as slow as its slowest folder.
 *
 * The window calls this once per folder row and fills each in as it answers, so
 * a large untouched tree delays nothing but its own row.
 * FolderVerdict is what was concluded about one folder, and why not, when it
 * could not be concluded.
 */
export class FolderVerdict {
    "status": string;

    /**
     * Why is empty unless the walk gave up. It is carried back rather than only
     * logged, because somebody looking at "could not check" wants to know why
     * without going to find a log file — and because the application knowing and
     * discarding it is what made three wrong guesses possible.
     */
    "why"?: string;

    /** Creates a new FolderVerdict instance. */
    constructor($$source: Partial<FolderVerdict> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FolderVerdict instance from a string or object.
     */
    static createFrom($$source: any = {}): FolderVerdict {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FolderVerdict($$parsedSource as Partial<FolderVerdict>);
    }
}

/**
 * Health is the whole answer, shaped for one panel and one menu.
 */
export class Health {
    "level": Level;
    "headline": string;

    /**
     * Version is the build the window is talking to, which is not necessarily the
     * one someone thinks they installed: a copy in /Applications and a working
     * build in bin/ share a bundle identifier, and the launchd agents run whichever
     * path was installed. Showing it costs a line and settles that question.
     */
    "version": string;

    /**
     * Findings are the specific things wrong, worst first. Empty when all is
     * well, so the panel has nothing to say rather than something reassuring.
     */
    "findings": Finding[];
    "snapshotCount": number;
    "newest"?: string | null;
    "oldest"?: string | null;

    /**
     * CoverageHours is the span between the oldest and newest snapshot: how far
     * back a mistake can be undone, which is the number the user actually wants.
     */
    "coverageHours": number;
    "scheduleInstalled": boolean;

    /**
     * ScheduleProgram is the binary the installed plist names, and
     * ScheduleProgramMissing says it is gone. Kept separate from Installed
     * because launchd reports a job whose program has vanished as installed and
     * loaded, and it is neither working nor obviously broken.
     */
    "scheduleProgram": string;
    "scheduleProgramMissing": boolean;
    "scheduleRunning": boolean;
    "intervalHours": number;
    "retentionDays": number;

    /**
     * ScheduleHeadline is the schedule in one line: which retention mode, how
     * often, and how far back. RetentionSummary is the same thing said in full,
     * for somewhere with room for a sentence.
     *
     * Both are worded by internal/schedule and carried here rather than built by
     * each reader. The menu bar built its own from IntervalHours and RetentionDays
     * alone, which ignores the policy: a tiered schedule was announced as "every
     * 3 hours, kept 364 days" when only one snapshot every four weeks survives
     * past the twenty-sixth. Two places wording one fact is how they came to
     * disagree, so now there is one.
     */
    "scheduleHeadline": string;
    "retentionSummary": string;

    /**
     * RetentionMode is just the name of the shape — "Flat window", "Tiered —
     * daily, then weekly" — for the places with room for a label and not a line.
     * The window's figure grid is four columns wide, so it shows this and carries
     * the headline in the cell's tooltip.
     */
    "retentionMode": string;

    /**
     * NextDue is when the schedule should next fire, estimated from the newest
     * snapshot. launchd fires a missed interval on wake, so a past value means
     * overdue rather than skipped.
     */
    "nextDue"?: string | null;
    "volumeTotalBytes": number;
    "volumeFreeBytes": number;
    "freePercent": number;

    /**
     * PurgeableCount is how many snapshots macOS may delete without asking.
     */
    "purgeableCount": number;

    /**
     * PinningStamp names the snapshot holding the container's minimum size up,
     * which is the one worth deleting first when space runs short.
     */
    "pinningStamp"?: string;

    /**
     * Volumes is every mounted APFS volume holding local snapshots, the data
     * volume among them.
     *
     * More than one, always, on a machine with anything plugged in. `tmutil
     * localsnapshot` takes no arguments and writes to all of them, and this
     * screen reported the data volume alone — so an external disk could fill with
     * snapshots this application had taken and nothing here would say so. The one
     * that found it was at 98% full with its own pinning snapshot, while the
     * figures above described a boot volume that was fine.
     */
    "volumes": VolumeHealth[];

    /**
     * TripwireInstalled and TripwireRunning describe the bulk-deletion watcher.
     * It is reported separately from the schedule because it covers a different
     * failure: the schedule bounds how much time you can lose, the tripwire
     * bounds how much of a single deletion you can lose.
     */
    "tripwireInstalled": boolean;
    "tripwireRunning": boolean;

    /**
     * TripwireWatching is how many directories it is set to watch.
     *
     * Reported because zero is a distinct kind of not-working from not-installed,
     * and the two need different advice: one is a button, the other is a decision
     * only the person using the machine can make. Without this, a screen offering
     * "install the watcher" would install one that watches nothing.
     */
    "tripwireWatching": number;

    /**
     * Faking reports that mounts are simulated and nothing under a mountpoint
     * is real.
     */
    "faking": boolean;

    /**
     * Scenario names the simulated machine these readings describe, empty when
     * they describe this one.
     */
    "scenario"?: string;

    /** Creates a new Health instance. */
    constructor($$source: Partial<Health> = {}) {
        if (!("level" in $$source)) {
            this["level"] = Level.$zero;
        }
        if (!("headline" in $$source)) {
            this["headline"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("findings" in $$source)) {
            this["findings"] = [];
        }
        if (!("snapshotCount" in $$source)) {
            this["snapshotCount"] = 0;
        }
        if (!("coverageHours" in $$source)) {
            this["coverageHours"] = 0;
        }
        if (!("scheduleInstalled" in $$source)) {
            this["scheduleInstalled"] = false;
        }
        if (!("scheduleProgram" in $$source)) {
            this["scheduleProgram"] = "";
        }
        if (!("scheduleProgramMissing" in $$source)) {
            this["scheduleProgramMissing"] = false;
        }
        if (!("scheduleRunning" in $$source)) {
            this["scheduleRunning"] = false;
        }
        if (!("intervalHours" in $$source)) {
            this["intervalHours"] = 0;
        }
        if (!("retentionDays" in $$source)) {
            this["retentionDays"] = 0;
        }
        if (!("scheduleHeadline" in $$source)) {
            this["scheduleHeadline"] = "";
        }
        if (!("retentionSummary" in $$source)) {
            this["retentionSummary"] = "";
        }
        if (!("retentionMode" in $$source)) {
            this["retentionMode"] = "";
        }
        if (!("volumeTotalBytes" in $$source)) {
            this["volumeTotalBytes"] = 0;
        }
        if (!("volumeFreeBytes" in $$source)) {
            this["volumeFreeBytes"] = 0;
        }
        if (!("freePercent" in $$source)) {
            this["freePercent"] = 0;
        }
        if (!("purgeableCount" in $$source)) {
            this["purgeableCount"] = 0;
        }
        if (!("volumes" in $$source)) {
            this["volumes"] = [];
        }
        if (!("tripwireInstalled" in $$source)) {
            this["tripwireInstalled"] = false;
        }
        if (!("tripwireRunning" in $$source)) {
            this["tripwireRunning"] = false;
        }
        if (!("tripwireWatching" in $$source)) {
            this["tripwireWatching"] = 0;
        }
        if (!("faking" in $$source)) {
            this["faking"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Health instance from a string or object.
     */
    static createFrom($$source: any = {}): Health {
        const $$createField3_0 = $$createType2;
        const $$createField23_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("findings" in $$parsedSource) {
            $$parsedSource["findings"] = $$createField3_0($$parsedSource["findings"]);
        }
        if ("volumes" in $$parsedSource) {
            $$parsedSource["volumes"] = $$createField23_0($$parsedSource["volumes"]);
        }
        return new Health($$parsedSource as Partial<Health>);
    }
}

/**
 * Level is how worried to be, and drives nothing but presentation.
 */
export enum Level {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * LevelOK means snapshots exist and something is taking more.
     */
    LevelOK = "ok",

    /**
     * LevelWarn means protection exists but is degraded or is quietly lying
     * about its retention.
     */
    LevelWarn = "warn",

    /**
     * LevelBad means there is no usable rollback point, or nothing is taking
     * any.
     */
    LevelBad = "bad",

    /**
     * LevelInfo is something the panel should say that is not a degradation.
     *
     * It exists for one reason: a scenario has to announce itself in the findings,
     * and if that announcement escalated the verdict then the clean "nothing to
     * say" state could never be reached under a scenario — which is one of the
     * states a scenario is most useful for driving the interface into.
     */
    LevelInfo = "info",
};

/**
 * Listing is one directory's contents, on one side.
 */
export class Listing {
    /**
     * LivePath is the location in the running system's terms, which is what
     * the user recognises even when reading a snapshot.
     */
    "livePath": string;
    "parent": string;

    /**
     * Root is the highest folder this volume's snapshots say anything about: "/"
     * for the startup disk, and the mount point for any other.
     *
     * Sent so the window can stop offering folders above it. The trail across the
     * top used to read "/ › Volumes › sdcard256gb › projects" for a snapshot of an
     * SD card, with the first two clickable and leading straight to an error
     * saying that volume's snapshots do not cover them.
     */
    "root": string;
    "entries": vfs$0.Entry[];

    /**
     * Covered is false for paths no snapshot of the data volume contains, such
     * as external disks or the sealed system volume.
     */
    "covered": boolean;
    "note"?: string;

    /** Creates a new Listing instance. */
    constructor($$source: Partial<Listing> = {}) {
        if (!("livePath" in $$source)) {
            this["livePath"] = "";
        }
        if (!("parent" in $$source)) {
            this["parent"] = "";
        }
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("entries" in $$source)) {
            this["entries"] = [];
        }
        if (!("covered" in $$source)) {
            this["covered"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Listing instance from a string or object.
     */
    static createFrom($$source: any = {}): Listing {
        const $$createField3_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField3_0($$parsedSource["entries"]);
        }
        return new Listing($$parsedSource as Partial<Listing>);
    }
}

/**
 * MergedListing is one directory shown from both sides at once, with every
 * entry already marked as unchanged, changed, deleted or new.
 */
export class MergedListing {
    "livePath": string;
    "parent": string;

    /**
     * Root is the highest folder this volume's snapshots say anything about: "/"
     * for the startup disk, and the mount point for any other.
     *
     * Sent so the window can stop offering folders above it. The trail across the
     * top used to read "/ › Volumes › sdcard256gb › projects" for a snapshot of an
     * SD card, with the first two clickable and leading straight to an error
     * saying that volume's snapshots do not cover them.
     */
    "root": string;
    "rows": diffs$0.Change[];

    /**
     * SnapshotExists and LiveExists distinguish an empty folder from one that
     * was not there at all, which is the difference between "nothing was lost"
     * and "the whole folder is gone".
     */
    "snapshotExists": boolean;
    "liveExists": boolean;
    "note"?: string;

    /** Creates a new MergedListing instance. */
    constructor($$source: Partial<MergedListing> = {}) {
        if (!("livePath" in $$source)) {
            this["livePath"] = "";
        }
        if (!("parent" in $$source)) {
            this["parent"] = "";
        }
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("snapshotExists" in $$source)) {
            this["snapshotExists"] = false;
        }
        if (!("liveExists" in $$source)) {
            this["liveExists"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergedListing instance from a string or object.
     */
    static createFrom($$source: any = {}): MergedListing {
        const $$createField3_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField3_0($$parsedSource["rows"]);
        }
        return new MergedListing($$parsedSource as Partial<MergedListing>);
    }
}

/**
 * Overview is everything the main screen needs in one call.
 */
export class Overview {
    /**
     * Snapshots is the data volume's, which is what the browsing screens work
     * against. Kept alongside Volumes rather than derived from it, because those
     * screens are about one volume by nature: they compare a snapshot with the
     * live disk, and the live disk they mean is this one.
     */
    "snapshots": SnapshotView[];

    /**
     * Volumes is every volume's, grouped, for the list.
     */
    "volumes": VolumeSnapshots[];

    /**
     * TimeMachineWarning is set when Time Machine has a destination, because
     * backupd then thins these same snapshots to roughly a day and any longer
     * retention shown elsewhere would be a lie.
     */
    "timeMachineWarning": string;
    "volumeTotalBytes": number;
    "volumeFreeBytes": number;

    /** Creates a new Overview instance. */
    constructor($$source: Partial<Overview> = {}) {
        if (!("snapshots" in $$source)) {
            this["snapshots"] = [];
        }
        if (!("volumes" in $$source)) {
            this["volumes"] = [];
        }
        if (!("timeMachineWarning" in $$source)) {
            this["timeMachineWarning"] = "";
        }
        if (!("volumeTotalBytes" in $$source)) {
            this["volumeTotalBytes"] = 0;
        }
        if (!("volumeFreeBytes" in $$source)) {
            this["volumeFreeBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Overview instance from a string or object.
     */
    static createFrom($$source: any = {}): Overview {
        const $$createField0_0 = $$createType10;
        const $$createField1_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("snapshots" in $$parsedSource) {
            $$parsedSource["snapshots"] = $$createField0_0($$parsedSource["snapshots"]);
        }
        if ("volumes" in $$parsedSource) {
            $$parsedSource["volumes"] = $$createField1_0($$parsedSource["volumes"]);
        }
        return new Overview($$parsedSource as Partial<Overview>);
    }
}

/**
 * PolicyOption is one retention policy on offer, with what it would actually do
 * at the interval currently chosen.
 *
 * The numbers are the point. "Hourly for a day, daily for a week" tells nobody
 * whether they end up with more or fewer restore points than they have now,
 * which is the only question anyone actually has about retention.
 */
export class PolicyOption {
    "id": string;
    "name": string;
    "summary": string;
    "tiers": TierView[];

    /**
     * Retained is how many snapshots the policy holds once the schedule has been
     * running longer than the policy reaches, counted by planning a history at
     * this interval so it cannot drift from the code that deletes.
     */
    "retained": number;

    /**
     * ReachDays is the age of the oldest snapshot still kept.
     */
    "reachDays": number;

    /** Creates a new PolicyOption instance. */
    constructor($$source: Partial<PolicyOption> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("tiers" in $$source)) {
            this["tiers"] = [];
        }
        if (!("retained" in $$source)) {
            this["retained"] = 0;
        }
        if (!("reachDays" in $$source)) {
            this["reachDays"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PolicyOption instance from a string or object.
     */
    static createFrom($$source: any = {}): PolicyOption {
        const $$createField3_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tiers" in $$parsedSource) {
            $$parsedSource["tiers"] = $$createField3_0($$parsedSource["tiers"]);
        }
        return new PolicyOption($$parsedSource as Partial<PolicyOption>);
    }
}

/**
 * Presence records whether one path exists in one snapshot.
 */
export class Presence {
    "snapshot": string;
    "stamp": string;
    "mounted": boolean;

    /**
     * Present is meaningful only when Mounted is true; an unmounted snapshot
     * cannot be inspected without authorization.
     */
    "present": boolean;
    "size": number;

    /** Creates a new Presence instance. */
    constructor($$source: Partial<Presence> = {}) {
        if (!("snapshot" in $$source)) {
            this["snapshot"] = "";
        }
        if (!("stamp" in $$source)) {
            this["stamp"] = "";
        }
        if (!("mounted" in $$source)) {
            this["mounted"] = false;
        }
        if (!("present" in $$source)) {
            this["present"] = false;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Presence instance from a string or object.
     */
    static createFrom($$source: any = {}): Presence {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Presence($$parsedSource as Partial<Presence>);
    }
}

/**
 * RestoreRequest asks for one path to be brought back.
 */
export class RestoreRequest {
    "snapshot": string;

    /**
     * Device names the volume the snapshot is on, empty meaning the startup disk.
     *
     * The snapshot name does not say: the same date exists on every volume mounted
     * when it was taken, and both copies can be attached at once. Restoring from
     * the wrong one would write another disk's file over this one's.
     */
    "device": string;

    /**
     * LivePath is where the file belongs. In the default mode the restored
     * copy lands beside it rather than on it.
     */
    "livePath": string;

    /**
     * Replace puts the restored copy at the original path, moving whatever is
     * there to a .bak- copy first. Nothing is ever deleted.
     */
    "replace": boolean;

    /** Creates a new RestoreRequest instance. */
    constructor($$source: Partial<RestoreRequest> = {}) {
        if (!("snapshot" in $$source)) {
            this["snapshot"] = "";
        }
        if (!("device" in $$source)) {
            this["device"] = "";
        }
        if (!("livePath" in $$source)) {
            this["livePath"] = "";
        }
        if (!("replace" in $$source)) {
            this["replace"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RestoreRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): RestoreRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RestoreRequest($$parsedSource as Partial<RestoreRequest>);
    }
}

/**
 * Restored says what Restore put back, so the caller can tell someone.
 */
export class Restored {
    "schedule": boolean;
    "tripwire": boolean;

    /** Creates a new Restored instance. */
    constructor($$source: Partial<Restored> = {}) {
        if (!("schedule" in $$source)) {
            this["schedule"] = false;
        }
        if (!("tripwire" in $$source)) {
            this["tripwire"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Restored instance from a string or object.
     */
    static createFrom($$source: any = {}): Restored {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Restored($$parsedSource as Partial<Restored>);
    }
}

/**
 * ScheduleView is the schedule as the settings screen shows it.
 */
export class ScheduleView {
    "installed": boolean;
    "loaded": boolean;

    /**
     * IntervalHours and RetentionDays are the units the interface offers,
     * rather than the durations stored underneath.
     */
    "intervalHours": number;
    "retentionDays": number;
    "plistPath": string;
    "logPath": string;
    "conflicts": string[];

    /**
     * MaxSnapshots is how many the schedule will hold at this interval and
     * retention, which is the number worth seeing before committing to a
     * setting. Counted by planning a history rather than by dividing the window
     * by the interval, because with a tiered policy those are different numbers
     * and only the first one is true.
     */
    "maxSnapshots": number;

    /**
     * PolicyID names the retention policy in force, so the settings screen can
     * preselect it: "flat", a preset's identifier, or "custom" for a plist
     * somebody edited by hand.
     */
    "policyId": string;

    /**
     * PolicySummary is the policy as a sentence, worded in one place so the
     * interface never has to word durations a second time.
     */
    "policySummary": string;

    /**
     * ReachDays is how far back the retained history goes. For a flat window it
     * is RetentionDays; for a tiered policy it is much further, and it is the
     * number the whole argument for tiering rests on.
     */
    "reachDays": number;
    "tiers": TierView[];

    /** Creates a new ScheduleView instance. */
    constructor($$source: Partial<ScheduleView> = {}) {
        if (!("installed" in $$source)) {
            this["installed"] = false;
        }
        if (!("loaded" in $$source)) {
            this["loaded"] = false;
        }
        if (!("intervalHours" in $$source)) {
            this["intervalHours"] = 0;
        }
        if (!("retentionDays" in $$source)) {
            this["retentionDays"] = 0;
        }
        if (!("plistPath" in $$source)) {
            this["plistPath"] = "";
        }
        if (!("logPath" in $$source)) {
            this["logPath"] = "";
        }
        if (!("conflicts" in $$source)) {
            this["conflicts"] = [];
        }
        if (!("maxSnapshots" in $$source)) {
            this["maxSnapshots"] = 0;
        }
        if (!("policyId" in $$source)) {
            this["policyId"] = "";
        }
        if (!("policySummary" in $$source)) {
            this["policySummary"] = "";
        }
        if (!("reachDays" in $$source)) {
            this["reachDays"] = 0;
        }
        if (!("tiers" in $$source)) {
            this["tiers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScheduleView instance from a string or object.
     */
    static createFrom($$source: any = {}): ScheduleView {
        const $$createField6_0 = $$createType15;
        const $$createField11_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("conflicts" in $$parsedSource) {
            $$parsedSource["conflicts"] = $$createField6_0($$parsedSource["conflicts"]);
        }
        if ("tiers" in $$parsedSource) {
            $$parsedSource["tiers"] = $$createField11_0($$parsedSource["tiers"]);
        }
        return new ScheduleView($$parsedSource as Partial<ScheduleView>);
    }
}

/**
 * SearchResult is every match, plus an honest account of what was not looked at.
 */
export class SearchResult {
    "term": string;
    "hits": find$0.Hit[];

    /**
     * Searched and Skipped name the snapshots that were and were not looked
     * inside. An unmounted snapshot cannot be searched, and saying so is the
     * difference between "it is not there" and "nobody looked".
     */
    "searched": string[];
    "skipped": string[];

    /**
     * Truncated reports that a limit stopped the walk, so absence here proves
     * nothing.
     */
    "truncated": boolean;

    /**
     * Incomplete reports that the walk ran out of budget before it ran out of
     * tree. Distinct from Truncated: there were not too many answers, there was
     * too much to read, and the advice differs.
     */
    "incomplete": boolean;
    "note"?: string;

    /** Creates a new SearchResult instance. */
    constructor($$source: Partial<SearchResult> = {}) {
        if (!("term" in $$source)) {
            this["term"] = "";
        }
        if (!("hits" in $$source)) {
            this["hits"] = [];
        }
        if (!("searched" in $$source)) {
            this["searched"] = [];
        }
        if (!("skipped" in $$source)) {
            this["skipped"] = [];
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }
        if (!("incomplete" in $$source)) {
            this["incomplete"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResult {
        const $$createField1_0 = $$createType17;
        const $$createField2_0 = $$createType15;
        const $$createField3_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hits" in $$parsedSource) {
            $$parsedSource["hits"] = $$createField1_0($$parsedSource["hits"]);
        }
        if ("searched" in $$parsedSource) {
            $$parsedSource["searched"] = $$createField2_0($$parsedSource["searched"]);
        }
        if ("skipped" in $$parsedSource) {
            $$parsedSource["skipped"] = $$createField3_0($$parsedSource["skipped"]);
        }
        return new SearchResult($$parsedSource as Partial<SearchResult>);
    }
}

/**
 * SnapshotComparison is the difference between two snapshots, with the two ends
 * named so that no row can be read backwards.
 *
 * diffs.Change names its fields for a snapshot-against-live comparison, and here
 * they mean: AbsSnapshot, SnapSize and SnapModTime describe Older, while AbsLive,
 * LiveSize and LiveModTime describe Newer. Status follows from that —
 * OnlyInSnapshot is an entry that was gone by the newer snapshot, OnlyOnDisk one
 * that had appeared by then. Nothing in diffs has to change for this to hold,
 * because it compares two directories and never asks what either one is; but the
 * mapping is worth stating, since a reader of the interface would otherwise have
 * to infer it from field names that no longer describe the question.
 */
export class SnapshotComparison {
    "older": SnapshotView;
    "newer": SnapshotView;

    /**
     * Swapped reports that the request had the two the wrong way round and the
     * roles above were corrected. The interface can then show the direction it
     * actually got rather than the one it asked for.
     */
    "swapped": boolean;

    /**
     * LivePath is the folder that was compared, in the running system's terms.
     * Neither side's absolute paths are live paths, so this is what a restore
     * from either of them has to be rebuilt against.
     */
    "livePath": string;
    "result": diffs$0.Result;

    /** Creates a new SnapshotComparison instance. */
    constructor($$source: Partial<SnapshotComparison> = {}) {
        if (!("older" in $$source)) {
            this["older"] = (new SnapshotView());
        }
        if (!("newer" in $$source)) {
            this["newer"] = (new SnapshotView());
        }
        if (!("swapped" in $$source)) {
            this["swapped"] = false;
        }
        if (!("livePath" in $$source)) {
            this["livePath"] = "";
        }
        if (!("result" in $$source)) {
            this["result"] = (new diffs$0.Result());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SnapshotComparison instance from a string or object.
     */
    static createFrom($$source: any = {}): SnapshotComparison {
        const $$createField0_0 = $$createType9;
        const $$createField1_0 = $$createType9;
        const $$createField4_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("older" in $$parsedSource) {
            $$parsedSource["older"] = $$createField0_0($$parsedSource["older"]);
        }
        if ("newer" in $$parsedSource) {
            $$parsedSource["newer"] = $$createField1_0($$parsedSource["newer"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField4_0($$parsedSource["result"]);
        }
        return new SnapshotComparison($$parsedSource as Partial<SnapshotComparison>);
    }
}

/**
 * SnapshotView is one snapshot as the frontend sees it.
 */
export class SnapshotView {
    "name": string;
    "stamp": string;
    "taken": string;

    /**
     * Device and UUID identify this COPY, on this volume.
     *
     * The same date exists on every volume mounted when it was taken, because
     * `tmutil localsnapshot` writes to all of them at once. So a row in a list is
     * not a date, it is one volume's copy of a date, and deleting it must not take
     * the others with it. The UUID is the only identifier that can tell them
     * apart; the stamp cannot.
     */
    "device": string;
    "uuid": string;

    /**
     * Purgeable reports that macOS may reclaim this copy without being asked.
     */
    "purgeable": boolean;

    /**
     * LimitsContainer marks the copy holding this volume's container at its
     * current size, which is the one whose deletion actually returns space.
     */
    "limitsContainer": boolean;

    /**
     * Mounted and MountPoint describe whether the contents can be read right
     * now. Mounting is the only step that needs authorization.
     */
    "mounted": boolean;
    "mountPoint": string;

    /** Creates a new SnapshotView instance. */
    constructor($$source: Partial<SnapshotView> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("stamp" in $$source)) {
            this["stamp"] = "";
        }
        if (!("taken" in $$source)) {
            this["taken"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("device" in $$source)) {
            this["device"] = "";
        }
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }
        if (!("purgeable" in $$source)) {
            this["purgeable"] = false;
        }
        if (!("limitsContainer" in $$source)) {
            this["limitsContainer"] = false;
        }
        if (!("mounted" in $$source)) {
            this["mounted"] = false;
        }
        if (!("mountPoint" in $$source)) {
            this["mountPoint"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SnapshotView instance from a string or object.
     */
    static createFrom($$source: any = {}): SnapshotView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SnapshotView($$parsedSource as Partial<SnapshotView>);
    }
}

/**
 * TierView is one band of a retention policy in the units the interface uses.
 */
export class TierView {
    /**
     * EveryHours is zero for a band that keeps every snapshot it covers.
     */
    "everyHours": number;
    "forHours": number;

    /** Creates a new TierView instance. */
    constructor($$source: Partial<TierView> = {}) {
        if (!("everyHours" in $$source)) {
            this["everyHours"] = 0;
        }
        if (!("forHours" in $$source)) {
            this["forHours"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TierView instance from a string or object.
     */
    static createFrom($$source: any = {}): TierView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TierView($$parsedSource as Partial<TierView>);
    }
}

/**
 * TripwireSensitivity is one setting on offer, with the count it stands for.
 *
 * The count is carried rather than worded here: "75 files" means something next to
 * a name, and the window can put the two together in its own language.
 */
export class TripwireSensitivity {
    "id": string;

    /**
     * Deletions is how many inside the window count as a burst.
     */
    "deletions": number;

    /**
     * WindowSeconds is the same for every setting, and is here so the window can
     * say "within five seconds" without knowing the number itself.
     */
    "windowSeconds": number;

    /** Creates a new TripwireSensitivity instance. */
    constructor($$source: Partial<TripwireSensitivity> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("deletions" in $$source)) {
            this["deletions"] = 0;
        }
        if (!("windowSeconds" in $$source)) {
            this["windowSeconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TripwireSensitivity instance from a string or object.
     */
    static createFrom($$source: any = {}): TripwireSensitivity {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TripwireSensitivity($$parsedSource as Partial<TripwireSensitivity>);
    }
}

/**
 * TripwireView is the bulk-deletion watcher as the settings screen shows it.
 */
export class TripwireView {
    "installed": boolean;
    "running": boolean;
    "plistPath": string;
    "logPath": string;

    /** Creates a new TripwireView instance. */
    constructor($$source: Partial<TripwireView> = {}) {
        if (!("installed" in $$source)) {
            this["installed"] = false;
        }
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("plistPath" in $$source)) {
            this["plistPath"] = "";
        }
        if (!("logPath" in $$source)) {
            this["logPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TripwireView instance from a string or object.
     */
    static createFrom($$source: any = {}): TripwireView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TripwireView($$parsedSource as Partial<TripwireView>);
    }
}

/**
 * VolumeHealth is one APFS volume's own numbers.
 *
 * Its own, because the container is its own: an external disk has its own free
 * space and its own pinning snapshot, and neither is knowable from the boot
 * volume's. Reporting one volume's figures for a machine that snapshots several
 * is not an approximation, it is an answer about a different disk.
 */
export class VolumeHealth {
    /**
     * MountPoint is where it is attached, which is the name a person knows it by.
     */
    "mountPoint": string;

    /**
     * Device is the volume identifier, like "disk8s1". Two mount points can name
     * one volume, so this is what makes a row distinct.
     */
    "device": string;

    /**
     * SnapshotCount is how many local snapshots it holds.
     */
    "snapshotCount": number;

    /**
     * PurgeableCount is how many of those macOS may reclaim on its own.
     */
    "purgeableCount": number;

    /**
     * PinningStamp names the one holding this container's minimum size up.
     */
    "pinningStamp"?: string;
    "totalBytes": number;
    "freeBytes": number;
    "freePercent": number;

    /** Creates a new VolumeHealth instance. */
    constructor($$source: Partial<VolumeHealth> = {}) {
        if (!("mountPoint" in $$source)) {
            this["mountPoint"] = "";
        }
        if (!("device" in $$source)) {
            this["device"] = "";
        }
        if (!("snapshotCount" in $$source)) {
            this["snapshotCount"] = 0;
        }
        if (!("purgeableCount" in $$source)) {
            this["purgeableCount"] = 0;
        }
        if (!("totalBytes" in $$source)) {
            this["totalBytes"] = 0;
        }
        if (!("freeBytes" in $$source)) {
            this["freeBytes"] = 0;
        }
        if (!("freePercent" in $$source)) {
            this["freePercent"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VolumeHealth instance from a string or object.
     */
    static createFrom($$source: any = {}): VolumeHealth {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VolumeHealth($$parsedSource as Partial<VolumeHealth>);
    }
}

/**
 * VolumeSnapshots is one volume's snapshots, under the name of the disk.
 *
 * The list is grouped because the snapshots are: `tmutil localsnapshot` takes no
 * arguments and writes to every mounted APFS volume at once, so an ungrouped list
 * of one volume's copies was most of a machine's snapshots missing. There was no
 * way to see the ones on an external disk at all.
 */
export class VolumeSnapshots {
    /**
     * Name is what the disk is called — "sdcard256gb" — which is the heading a
     * person recognises. MountPoint and Device are what commands are addressed
     * with, and are shown beside it because two mount points can name one volume.
     */
    "name": string;
    "mountPoint": string;
    "device": string;

    /**
     * IsStartupDisk marks the data volume, which is the only one whose snapshots
     * can be browsed, compared and restored from here. Everything else can be
     * listed and deleted, and opening one is on the way.
     */
    "isStartupDisk": boolean;
    "snapshots": SnapshotView[];
    "freeBytes": number;
    "totalBytes": number;

    /** Creates a new VolumeSnapshots instance. */
    constructor($$source: Partial<VolumeSnapshots> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("mountPoint" in $$source)) {
            this["mountPoint"] = "";
        }
        if (!("device" in $$source)) {
            this["device"] = "";
        }
        if (!("isStartupDisk" in $$source)) {
            this["isStartupDisk"] = false;
        }
        if (!("snapshots" in $$source)) {
            this["snapshots"] = [];
        }
        if (!("freeBytes" in $$source)) {
            this["freeBytes"] = 0;
        }
        if (!("totalBytes" in $$source)) {
            this["totalBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VolumeSnapshots instance from a string or object.
     */
    static createFrom($$source: any = {}): VolumeSnapshots {
        const $$createField4_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("snapshots" in $$parsedSource) {
            $$parsedSource["snapshots"] = $$createField4_0($$parsedSource["snapshots"]);
        }
        return new VolumeSnapshots($$parsedSource as Partial<VolumeSnapshots>);
    }
}

/**
 * Warning is a bulk deletion the tripwire saw, as the window shows it.
 *
 * It comes from a file rather than from memory because the tripwire is a
 * separate process: by the time anyone opens the window, the process that saw
 * the deletion has long exited.
 */
export class Warning {
    "at": string;

    /**
     * Where names the folders the files went from, commonest first, as full
     * paths. This is what an ignore rule is built from: "~" means nothing to a
     * comparison against a path the filesystem reported.
     */
    "where": string[];

    /**
     * Labels is the same list written the way a person writes it, with the home
     * directory as "~". Both are sent because the interface shows one and acts on
     * the other, and deriving either in the window would mean teaching it where
     * home is.
     */
    "labels": string[];

    /**
     * Snapshot is the restore point taken in response. Empty means none was, and
     * Note says why.
     */
    "snapshot"?: string;
    "note"?: string;

    /** Creates a new Warning instance. */
    constructor($$source: Partial<Warning> = {}) {
        if (!("at" in $$source)) {
            this["at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("where" in $$source)) {
            this["where"] = [];
        }
        if (!("labels" in $$source)) {
            this["labels"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Warning instance from a string or object.
     */
    static createFrom($$source: any = {}): Warning {
        const $$createField1_0 = $$createType15;
        const $$createField2_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("where" in $$parsedSource) {
            $$parsedSource["where"] = $$createField1_0($$parsedSource["where"]);
        }
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField2_0($$parsedSource["labels"]);
        }
        return new Warning($$parsedSource as Partial<Warning>);
    }
}

/**
 * WatchedDirectories is the list as a screen should show it: what was configured,
 * and what it resolves to.
 *
 * Both, because they differ and the difference is the whole of some bug reports.
 * "~/projects" is what someone typed and recognises; "/Users/them/projects" is
 * what is actually being watched, and seeing it is how they find out that the
 * directory they meant is somewhere else.
 */
export class WatchedDirectory {
    "configured": string;
    "resolved": string;

    /**
     * Missing says the directory is not there. A watched directory that does not
     * exist is not watched, and nothing else on the screen would say so.
     */
    "missing": boolean;

    /** Creates a new WatchedDirectory instance. */
    constructor($$source: Partial<WatchedDirectory> = {}) {
        if (!("configured" in $$source)) {
            this["configured"] = "";
        }
        if (!("resolved" in $$source)) {
            this["resolved"] = "";
        }
        if (!("missing" in $$source)) {
            this["missing"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WatchedDirectory instance from a string or object.
     */
    static createFrom($$source: any = {}): WatchedDirectory {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WatchedDirectory($$parsedSource as Partial<WatchedDirectory>);
    }
}

// Private type creation functions
const $$createType0 = config$0.Config.createFrom;
const $$createType1 = Finding.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = VolumeHealth.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = vfs$0.Entry.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = diffs$0.Change.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = SnapshotView.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = VolumeSnapshots.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = TierView.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $Create.Array($Create.Any);
const $$createType16 = find$0.Hit.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = diffs$0.Result.createFrom;
