// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ScheduleService installs and inspects the timer that takes snapshots.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Install writes and loads the schedule with a flat retention window.
 *
 * It stays as it was, taking the two numbers and nothing else, because the
 * one-click fix in the Health panel calls it and installing a schedule must not
 * require an opinion about tiering first.
 */
export function Install(intervalHours: number, retentionDays: number): $CancellablePromise<$models.ScheduleView> {
    return $Call.ByID(223291454, intervalHours, retentionDays).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * InstallPolicy writes and loads the schedule with a chosen retention policy.
 * retentionDays is the flat window, and is used only when policyID names it —
 * every other policy carries its own bands.
 */
export function InstallPolicy(intervalHours: number, retentionDays: number, policyID: string): $CancellablePromise<$models.ScheduleView> {
    return $Call.ByID(3798770816, intervalHours, retentionDays, policyID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * InstallTripwire starts the watcher and keeps it started across logins.
 */
export function InstallTripwire(): $CancellablePromise<$models.TripwireView> {
    return $Call.ByID(3892613176).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Log returns the tail of the agent's log, so a schedule that is failing
 * silently can be seen to be failing.
 */
export function Log(maxBytes: number): $CancellablePromise<string> {
    return $Call.ByID(1268565191, maxBytes);
}

/**
 * Policies reports the retention policies on offer, each with what it would
 * retain at the interval and flat window currently chosen. The settings screen
 * calls it as those change, so the numbers beside each choice are always the
 * numbers for the schedule being configured.
 */
export function Policies(intervalHours: number, retentionDays: number): $CancellablePromise<$models.PolicyOption[]> {
    return $Call.ByID(1023449749, intervalHours, retentionDays).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Restore reinstalls whatever the settings say was asked for and launchd no
 * longer has.
 *
 * A launchd job is not durable in the way people assume. Upgrading through
 * Homebrew removes it, because the cask's uninstall stanza unloads both agents
 * before the new version is staged; so does anything else that tidies
 * ~/Library/LaunchAgents. The failure is silent and it is the worst one this
 * application has: the window still shows the interval that was chosen, the
 * settings file still records it, and nothing is taking snapshots.
 *
 * So the settings file is treated as the intent and launchd as the current
 * state, and this reconciles the second to the first. It only ever ADDS: a
 * schedule that was deliberately removed sets Enabled to false, and is not put
 * back.
 */
export function Restore(): $CancellablePromise<$models.Restored> {
    return $Call.ByID(2235634351).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * Status reports what launchd currently has.
 */
export function Status(): $CancellablePromise<$models.ScheduleView> {
    return $Call.ByID(3875547921).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * TripwireLog returns the tail of the watcher's log, which is the only way to
 * see that it is running and what it has reacted to.
 */
export function TripwireLog(maxBytes: number): $CancellablePromise<string> {
    return $Call.ByID(3485694905, maxBytes);
}

/**
 * TripwireStatus reports whether the watcher is installed and running.
 */
export function TripwireStatus(): $CancellablePromise<$models.TripwireView> {
    return $Call.ByID(2652651239).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Uninstall stops the schedule. Snapshots already taken are left alone.
 */
export function Uninstall(): $CancellablePromise<$models.ScheduleView> {
    return $Call.ByID(2821037115).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * UninstallTripwire stops the watcher. Snapshots it already took are left alone.
 */
export function UninstallTripwire(): $CancellablePromise<$models.TripwireView> {
    return $Call.ByID(573525833).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ScheduleView.createFrom;
const $$createType1 = $models.TripwireView.createFrom;
const $$createType2 = $models.PolicyOption.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.Restored.createFrom;
