// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SearchService answers the question that follows a deletion.
 *
 * Browse assumes you know where to look. After losing something you know what
 * it was called and roughly when it still existed, and almost never which
 * directory it was in. Every other screen here is organised by place; this one
 * is organised by name.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as diffs$0 from "../internal/diffs/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeletedSince lists what a folder held when the snapshot was taken and no
 * longer holds.
 *
 * This is the recovery view. Compare shows everything that differs, which after
 * a week of ordinary work is mostly noise; the only rows that matter when
 * something has gone missing are the ones that are gone.
 */
export function DeletedSince(device: string, snapshotName: string, livePath: string, deep: boolean): $CancellablePromise<diffs$0.Result> {
    return $Call.ByID(2851642391, device, snapshotName, livePath, deep).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Search looks inside every mounted snapshot for entries whose name contains
 * term.
 *
 * Only mounted snapshots can be searched, and rather than mounting on the user's
 * behalf — which costs an authorization prompt per batch — the unsearched ones
 * are named so the user can decide to open them.
 */
export function Search(term: string, under: string): $CancellablePromise<$models.SearchResult> {
    return $Call.ByID(1543671110, term, under).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = diffs$0.Result.createFrom;
const $$createType1 = $models.SearchResult.createFrom;
