// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SnapshotService lists, creates, deletes and mounts snapshots.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Delete removes a snapshot, identified by its date stamp. This is the one
 * irreversible action in the application: a deleted snapshot cannot be
 * recreated, because it recorded a past state of the disk.
 */
export function Delete(stamp: string): $CancellablePromise<void> {
    return $Call.ByID(2844585045, stamp);
}

/**
 * List returns the snapshots of the data volume, newest first.
 */
export function List(): $CancellablePromise<$models.SnapshotView[]> {
    return $Call.ByID(730783142).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Mount attaches snapshots so their contents can be read. One authorization
 * prompt covers the whole batch.
 */
export function Mount(names: string[]): $CancellablePromise<void> {
    return $Call.ByID(2362689787, names);
}

/**
 * Overview returns the snapshot list plus the context needed to read it
 * honestly: disk headroom, and whether Time Machine will thin the history.
 */
export function Overview(): $CancellablePromise<$models.Overview> {
    return $Call.ByID(1347408329).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * TakeNow creates a snapshot immediately. No authorization is needed: tmutil
 * asks backupd to do the work.
 */
export function TakeNow(): $CancellablePromise<$models.SnapshotView> {
    return $Call.ByID(2919724211).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Unmount detaches snapshots.
 */
export function Unmount(names: string[]): $CancellablePromise<void> {
    return $Call.ByID(153321518, names);
}

/**
 * UnmountAll detaches everything this application mounted, which is what the
 * window's close handler calls.
 */
export function UnmountAll(): $CancellablePromise<void> {
    return $Call.ByID(706770877);
}

// Private type creation functions
const $$createType0 = $models.SnapshotView.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.Overview.createFrom;
