// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SnapshotService lists, creates, deletes and mounts snapshots.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Delete removes ONE VOLUME'S COPY of a snapshot, identified by the volume it is
 * on and its identifier there. This is the one irreversible action in the
 * application: a deleted snapshot cannot be recreated, because it recorded a past
 * state of the disk.
 *
 * One copy, which is a change. It used to delete by date through tmutil, and
 * tmutil removes a date from every volume holding it — so deleting what looked
 * like one row took the external disk's snapshot of the same moment with it,
 * silently, because that snapshot was not on screen to begin with. Now that every
 * volume's copies are listed, a button beside one row has to mean that row.
 *
 * Retention still deletes by date, and should: a policy's verdict on a date is
 * the same on every volume, so removing it everywhere is the whole intent there.
 */
export function Delete(device: string, uuid: string, stamp: string): $CancellablePromise<void> {
    return $Call.ByID(2844585045, device, uuid, stamp);
}

/**
 * List returns the snapshots of the data volume, newest first.
 */
export function List(): $CancellablePromise<$models.SnapshotView[]> {
    return $Call.ByID(730783142).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Mount attaches snapshots so their contents can be read. One authorization
 * prompt covers the whole batch.
 *
 * device names which volume's copies to attach, because a date is not an
 * identity: every volume mounted when a snapshot was taken has one of that date.
 * Empty means the data volume, which is what the browsing screens ask for.
 */
export function Mount(device: string, names: string[]): $CancellablePromise<void> {
    return $Call.ByID(2362689787, device, names);
}

/**
 * Overview returns the snapshot list plus the context needed to read it
 * honestly: disk headroom, and whether Time Machine will thin the history.
 */
export function Overview(): $CancellablePromise<$models.Overview> {
    return $Call.ByID(1347408329).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * TakeNow creates a snapshot immediately. No authorization is needed: tmutil
 * asks backupd to do the work.
 *
 * One call, several snapshots: `tmutil localsnapshot` takes no arguments and
 * writes to every mounted APFS volume at once. What comes back describes the
 * startup disk's, which is the one the window selects and browses — the others
 * appear in their own groups on the next refresh. The mountpoint is the startup
 * disk's for the same reason, and is where this snapshot would attach rather
 * than where it has.
 */
export function TakeNow(): $CancellablePromise<$models.SnapshotView> {
    return $Call.ByID(2919724211).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Unmount detaches snapshots, on the volume named by device.
 */
export function Unmount(device: string, names: string[]): $CancellablePromise<void> {
    return $Call.ByID(153321518, device, names);
}

/**
 * UnmountAll detaches everything this application mounted, which is what the
 * window's close handler calls.
 *
 * Every volume, not the data volume. Leaving another volume's snapshots attached
 * would leave them undeletable — a mounted snapshot cannot be removed — and the
 * mountpoints would outlive the window that made them with nothing left offering
 * to close them.
 */
export function UnmountAll(): $CancellablePromise<void> {
    return $Call.ByID(706770877);
}

// Private type creation functions
const $$createType0 = $models.SnapshotView.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.Overview.createFrom;
