// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StatusService answers one question: is this Mac actually protected right now.
 * 
 * Every input already existed, scattered across the other services — the
 * snapshot list, the schedule, Time Machine's state, the free space. Scattered
 * is the problem: a user cannot assemble "I am covered" out of four screens, and
 * the failure this application exists to prevent is believing you are covered
 * when you are not.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Check gathers everything. It never fails on a partial answer: a system that
 * cannot report its free space should still say when the last snapshot was.
 */
export function Check(): $CancellablePromise<$models.Health> {
    return $Call.ByID(877487856).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * MountHelp is the explanation shown when mounting is refused, kept beside the
 * error it explains rather than written into the frontend.
 */
export function MountHelp(): $CancellablePromise<string> {
    return $Call.ByID(2793874858);
}

/**
 * OpenPrivacySettings reveals the Full Disk Access pane.
 * 
 * It exists because the mount failure it answers is otherwise a dead end: the
 * error names a permission, and the place to grant it is four levels into
 * System Settings.
 */
export function OpenPrivacySettings(): $CancellablePromise<void> {
    return $Call.ByID(380811309);
}

// Private type creation functions
const $$createType0 = $models.Health.createFrom;
