// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Appearance {
    /**
     * Theme is "system", "light" or "dark". "system" is a real value rather than
     * the absence of one, because following the system is a choice a person can
     * return to.
     */
    "theme": string;

    /**
     * Language is a two-letter code: "en", "de", "es" or "fr".
     *
     * It sits here rather than in its own section because it is the same kind of
     * setting as the theme — how the application presents itself, rather than what
     * it does. Both surfaces read it: the window translates its own text, and the
     * menu bar is redrawn through the settings watcher, so switching language
     * changes both without a relaunch.
     *
     * An unrecognised or empty value falls back to English rather than failing.
     * A settings file written by a later version, or edited by hand, should not
     * leave someone with an application that will not start.
     */
    "language": string;

    /** Creates a new Appearance instance. */
    constructor($$source: Partial<Appearance> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Appearance instance from a string or object.
     */
    static createFrom($$source: any = {}): Appearance {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Appearance($$parsedSource as Partial<Appearance>);
    }
}

/**
 * Config is the whole of it. Kept flat and small on purpose: every field here has
 * to be something a person would recognise as a choice they made.
 */
export class Config {
    "schedule": Schedule;
    "tripwire": Tripwire;
    "appearance": Appearance;
    "logging": Logging;
    "window": Window;
    "refresh": Refresh;
    "paths": Paths;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("schedule" in $$source)) {
            this["schedule"] = (new Schedule());
        }
        if (!("tripwire" in $$source)) {
            this["tripwire"] = (new Tripwire());
        }
        if (!("appearance" in $$source)) {
            this["appearance"] = (new Appearance());
        }
        if (!("logging" in $$source)) {
            this["logging"] = (new Logging());
        }
        if (!("window" in $$source)) {
            this["window"] = (new Window());
        }
        if (!("refresh" in $$source)) {
            this["refresh"] = (new Refresh());
        }
        if (!("paths" in $$source)) {
            this["paths"] = (new Paths());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType4;
        const $$createField5_0 = $$createType5;
        const $$createField6_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("schedule" in $$parsedSource) {
            $$parsedSource["schedule"] = $$createField0_0($$parsedSource["schedule"]);
        }
        if ("tripwire" in $$parsedSource) {
            $$parsedSource["tripwire"] = $$createField1_0($$parsedSource["tripwire"]);
        }
        if ("appearance" in $$parsedSource) {
            $$parsedSource["appearance"] = $$createField2_0($$parsedSource["appearance"]);
        }
        if ("logging" in $$parsedSource) {
            $$parsedSource["logging"] = $$createField3_0($$parsedSource["logging"]);
        }
        if ("window" in $$parsedSource) {
            $$parsedSource["window"] = $$createField4_0($$parsedSource["window"]);
        }
        if ("refresh" in $$parsedSource) {
            $$parsedSource["refresh"] = $$createField5_0($$parsedSource["refresh"]);
        }
        if ("paths" in $$parsedSource) {
            $$parsedSource["paths"] = $$createField6_0($$parsedSource["paths"]);
        }
        return new Config($$parsedSource as Partial<Config>);
    }
}

/**
 * Logging is what the application says about itself.
 */
export class Logging {
    /**
     * Verbose turns on per-directory and per-file logging.
     *
     * Off by default because it is tens of thousands of lines on a home folder.
     * On, it says why a folder could not be compared — which is the question that
     * prompted it, after three wrong guesses at an answer the application already
     * had and was discarding.
     */
    "verbose": boolean;

    /** Creates a new Logging instance. */
    constructor($$source: Partial<Logging> = {}) {
        if (!("verbose" in $$source)) {
            this["verbose"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Logging instance from a string or object.
     */
    static createFrom($$source: any = {}): Logging {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Logging($$parsedSource as Partial<Logging>);
    }
}

/**
 * Paths is where this application keeps things.
 *
 * Empty means the default location, which is what almost everyone wants; the
 * fields exist for the machine where /Users is not where the data lives. They are
 * resolved rather than used raw, so "~/somewhere" behaves as written.
 */
export class Paths {
    "mount_root": string;
    "log": string;
    "tripwire_log": string;

    /** Creates a new Paths instance. */
    constructor($$source: Partial<Paths> = {}) {
        if (!("mount_root" in $$source)) {
            this["mount_root"] = "";
        }
        if (!("log" in $$source)) {
            this["log"] = "";
        }
        if (!("tripwire_log" in $$source)) {
            this["tripwire_log"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Paths instance from a string or object.
     */
    static createFrom($$source: any = {}): Paths {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Paths($$parsedSource as Partial<Paths>);
    }
}

/**
 * Refresh is how often each surface re-reads state it did not change itself.
 *
 * Both exist because snapshots are taken by things that are not this window: the
 * menu bar, a launchd agent, and the bulk-deletion tripwire. Neither number is
 * about being live — the underlying state moves on the schedule's interval, hours
 * rather than seconds — so they are about noticing, and a slow machine or a large
 * snapshot count is a reason someone might want them longer.
 */
export class Refresh {
    "menu_bar_seconds": number;
    "window_seconds": number;

    /** Creates a new Refresh instance. */
    constructor($$source: Partial<Refresh> = {}) {
        if (!("menu_bar_seconds" in $$source)) {
            this["menu_bar_seconds"] = 0;
        }
        if (!("window_seconds" in $$source)) {
            this["window_seconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Refresh instance from a string or object.
     */
    static createFrom($$source: any = {}): Refresh {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Refresh($$parsedSource as Partial<Refresh>);
    }
}

/**
 * Schedule is what to ask launchd for, not what launchd is currently doing.
 */
export class Schedule {
    /**
     * Enabled says a schedule was ASKED for, which the numbers below cannot: a
     * fresh settings file carries defaults that are indistinguishable from a
     * deliberate choice of the same values. Without it, restoring "what was
     * configured" on launch would install a schedule for someone who never
     * wanted one.
     */
    "enabled": boolean;
    "interval_hours": number;
    "retention_days": number;

    /**
     * Policy names a retention preset — "flat" keeps everything inside the window,
     * the tiered ones thin with age. Stored by id rather than by its expansion so
     * that improving a preset improves existing configurations.
     */
    "policy": string;

    /** Creates a new Schedule instance. */
    constructor($$source: Partial<Schedule> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("interval_hours" in $$source)) {
            this["interval_hours"] = 0;
        }
        if (!("retention_days" in $$source)) {
            this["retention_days"] = 0;
        }
        if (!("policy" in $$source)) {
            this["policy"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Schedule instance from a string or object.
     */
    static createFrom($$source: any = {}): Schedule {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Schedule($$parsedSource as Partial<Schedule>);
    }
}

export class Tripwire {
    "enabled": boolean;

    /**
     * Ignore lists path fragments whose deletions do not count towards a burst.
     *
     * Without it the wire is tripped by ordinary machine noise: a browser
     * clearing its cache deletes hundreds of files in seconds, which is exactly
     * the shape of the thing being watched for and none of its meaning. A warning
     * that fires on cache churn is a warning someone learns to dismiss, and then
     * dismisses the one that mattered.
     *
     * Matched as substrings of the full path, after ~ is expanded, so a fragment
     * like "/Library/Caches/" covers every application's cache without naming any
     * of them.
     */
    "ignore": string[];

    /**
     * Sensitivity is how readily a burst counts as one worth snapshotting:
     * "cautious", "balanced", "sensitive" or "very-sensitive". Empty means
     * balanced, which is what every build before this setting existed used.
     *
     * A name rather than a count, because the count alone is unanswerable — whether
     * two hundred files in five seconds is a lot depends entirely on what the
     * machine does all day, which is the thing being configured.
     */
    "sensitivity": string;

    /** Creates a new Tripwire instance. */
    constructor($$source: Partial<Tripwire> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("ignore" in $$source)) {
            this["ignore"] = [];
        }
        if (!("sensitivity" in $$source)) {
            this["sensitivity"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tripwire instance from a string or object.
     */
    static createFrom($$source: any = {}): Tripwire {
        const $$createField1_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ignore" in $$parsedSource) {
            $$parsedSource["ignore"] = $$createField1_0($$parsedSource["ignore"]);
        }
        return new Tripwire($$parsedSource as Partial<Tripwire>);
    }
}

/**
 * Window is the size the window opens at.
 */
export class Window {
    "width": number;
    "height": number;

    /** Creates a new Window instance. */
    constructor($$source: Partial<Window> = {}) {
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Window instance from a string or object.
     */
    static createFrom($$source: any = {}): Window {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Window($$parsedSource as Partial<Window>);
    }
}

// Private type creation functions
const $$createType0 = Schedule.createFrom;
const $$createType1 = Tripwire.createFrom;
const $$createType2 = Appearance.createFrom;
const $$createType3 = Logging.createFrom;
const $$createType4 = Window.createFrom;
const $$createType5 = Refresh.createFrom;
const $$createType6 = Paths.createFrom;
const $$createType7 = $Create.Array($Create.Any);
